# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bs2VFvpgXQL79CxwITHJcM7t5oAknlrk
"""

!pip install timm tqdm scikit-learn pandas pillow torchvision torchaudio -q
print("✅ ALL PACKAGES INSTALLED!")

from google.colab import files
import os

print("📁 UPLOAD RESNET CSV FILE")
print("Required: task1_3_resnet18_full_onsite_submission.csv")

# Upload ResNet file
uploaded_resnet = files.upload()

# Extract filename
resnet_file = list(uploaded_resnet.keys())[0]
print(f"\n✅ ResNet file uploaded: {resnet_file}")

print("\n📁 UPLOAD EFFICIENTNET CSV FILE")
print("Required: task1_3_efficientnet_full_onsite_submission.csv")

# Upload EfficientNet file
uploaded_effnet = files.upload()

# Extract filename
effnet_file = list(uploaded_effnet.keys())[0]
print(f"\n✅ EfficientNet file uploaded: {effnet_file}")

# List current directory
print("\n📂 Current CSV files:")
!ls -la *.csv

import pandas as pd
import numpy as np
from sklearn.metrics import f1_score
from google.colab import files

# Load Task 1.3 CSVs
resnet = pd.read_csv("task1_3_resnet18_full_onsite_submission.csv")
effnet = pd.read_csv("task1_3_efficientnet_full_onsite_submission.csv")

Resnet_weight=0.6
Effeicenet_weight = 0.4

Rensemble = pd.DataFrame()
ensemble["id"] = resnet["id"]

# ensemble
for col in ["D", "G", "A"]:
    ensemble[col] = Resnet_weight * resnet[col] +  Effeicenet_weight * effnet[col]


# Apply thresholds
Threshold_values = np.array([0.45, 0.575, 0.8])  #tuned thresholds

for col, T in zip(["D", "G", "A"],Threshold_values):
    ensemble[col] = (ensemble[col] > T).astype(int)

# Save to Kaggle
ensemble.to_csv("task4-ensemble.csv", index=False)
files.download("task4-ensemble.csv")
print("Saved task4-ensemble.csv")